// eslint-disable-next-line no-undef
export default defineAppConfig({
  pages: [
    "pages/index/index",
    "pages/auditContractDetail/index",
    "pages/visit/index",
    "pages/visitDetail/index",
    "pages/auditDetail/index",
    "pages/audit/index",
    "pages/intention/index",
    "pages/intentionDetail/index",
    "pages/customer/index",
    "pages/customerDetail/index",
    "pages/login/index",
    "pages/register/index",
    "pages/personalCenter/index",
    "pages/cashFlow/index",
    "pages/productDetail/index",
    "pages/cart/index",
    "pages/order/index",
    "pages/orderDetail/index",
    "pages/goodsManagement/index",
    "pages/goodsManagementDetail/index",
    "pages/goodsManagementEdit/index",
    "pages/storesManagement/index",
    "pages/storesManagementDetail/index",
    "pages/accountSetting/index",
    "pages/personalInfoDetail/index",
    "pages/verification/index",
    "pages/verificationAdd/index",
    "pages/verificationDetail/index",
  ],
  tabBar: {
    list: [
      {
        iconPath: "./assets/image/tabbar-icon-home.png",
        selectedIconPath: "./assets/image/tabbar-icon-home-active.png",
        pagePath: "pages/index/index",
        text: "首页",
      },
      {
        iconPath: "./assets/image/tabbar-icon-order.png",
        selectedIconPath: "./assets/image/tabbar-icon-order-active.png",
        pagePath: "pages/order/index",
        text: "订单",
      },
      {
        iconPath: "./assets/image/tabbar-icon-personal.png",
        selectedIconPath: "./assets/image/tabbar-icon-personal-active.png",
        pagePath: "pages/personalCenter/index",
        text: "我的",
      },
    ],
    color: "#333",
    selectedColor: "#02BF7E",
    backgroundColor: "#fff",
    borderStyle: "black",
  },
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#eaf5ef",
    navigationBarTitleText: "恒冰商城",
    navigationBarTextStyle: "black",
    backgroundColor: "#ffffff",
  },
});
